name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true

      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            path: build/VulkanWindow
          - os: windows-latest
            path: build/MinSizeRel/VulkanWindow.exe

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure cmake
        run: >
          cmake 
          -B build
          -DCMAKE_BUILD_TYPE=MinSizeRel
  
      - name: Build release
        run: >
          cmake 
          --build build
          --config MinSizeRel
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: ${{ matrix.path }}

  release:
    name: Release
    runs-on: [ubuntu-latest]
    needs: [build]

    steps:
      - uses: actions/checkout@v4

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-latest

      - name: Release Build
        uses: softprops/action-gh-release@v2
        with:
          name: Release
          tag_name: ${{ github.run_id }}
          body: |
            **This release has been built by Github Actions**
            [Link to build](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          files: |
            VulkanWindow
            VulkanWindow.exe
