name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  windows:
    name: Windows build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
  
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
  
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: binary
        path: build/VulkanWindow.exe
    
  linux:
    name: Linux build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install packages
        run: sudo apt install libglfw3-dev gcc-multilib g++-multilib libvulkan-dev libxinerama-dev libxcursor-dev libxi-dev
  
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
  
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
  
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
  
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: build/VulkanWindow

  release:
    name: Release
    runs-on: [ubuntu-latest]
    needs: [ windows, linux ]

    steps:
      - uses: actions/checkout@v3
      
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: binary

      - name: Release Build
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: |
            **This release has been built by Github Actions**
            [Link to build](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          files: |
            VulkanWindow
            VulkanWindow.exe





